# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Rails.application.load_tasks

namespace :rabbitmq do
  desc "Setup routing"
  task :setup do
    require "bunny"

    conn = Bunny.new(threated: false)
    conn.start

    ch = conn.create_channel

    x = ch.fanout("sender.posts")

    q = ch.queue("receiver.posts", durable: true)

    q.bind("sender.posts")

    conn.close
  end
end