# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70c98b76082d0c7c678313794a722f074c2ae3316209012999cc7c0b47968afa19ce6c06cb751d788e55d771dc0acdf3fcd485bf8ee38da73e24ce8b5317c06c

test:
  secret_key_base: cd0b5216fada3d391b199d7e4f3c7621f3ff99b0a7b467002b1d0e80fd1ff4a7eb8f392a7936648932d0875d9299b8573e4fd543b157a2ab48932df39c8d3a6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
